Post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView

app_name='Post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

exam/urls.py
from django.urls import path
from exam import views
from exam.views import ExamDetailView, EvaluationDetailView, SolutionDetailView


app_name='exam'

urlpatterns = [

    path('', views.exam_list, name='exam_list'),
    path('upload_exam/', views.upload_exam, name='upload_exam'),
    path('evaluation/', views.exam_evaluation_list, name='evaluation_list'),
    path('<int:pk>/', ExamDetailView.as_view(), name='exam_detail'),
    path('evaluation/<int:pk>/', EvaluationDetailView.as_view(), name='solution_list'),
    path('evaluation/detail/<int:pk>', SolutionDetailView.as_view(), name='solution_detail'),
    path('evaluation/detail/algorithm', views.Algorithm_detail, name='algorithm_detail'),

]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from gradesApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gradesApp/',include('gradesApp.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('logout/',views.userLogout,name='logout'),
    path('studentDash/',views.studentDash,name='studentDash'),
    path('teacherDash/',views.teacherDash,name='teacherDash'),
    path('materials/', include('upload.urls')),
    path('post/', include('Post.urls')),
    path('assignment/', include('assignment.urls')),
    path('notice/', include('Notice.urls')),
    path('exam/', include('exam.urls')),
    path('zoom/', include('zoom.urls')),
    path('onlineExam/', include('onlineExam.urls')),
    path('chatbot/', include('chatbot.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

exam/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Exam(models.Model):
    title = models.TextField()
    body = models.TextField()
    sampleSolution = models.TextField()
    due = models.DateField()
    question = models.FileField(upload_to='exams/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class ExamSolution(models.Model):
    answer = models.TextField()
    submission_time = models.DateTimeField(default=timezone.now)
    problem = models.ForeignKey('Exam', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

exam/forms.py
from django import forms
from .models import Exam, ExamSolution


class DateInput(forms.DateInput):
    input_type = 'date'



class ExamForm(forms.ModelForm):
    title = forms.CharField(
        label='Name',
        widget=forms.Textarea(attrs={
            'rows': '1',
            'placeholder': 'Enter Exam Name',
            'class':'form-control'
            }))

    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...',
            'class':'form-control'
            }))

    sampleSol = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '5',
            'placeholder': 'Enter Sample Solution here...',
            'class':'form-control'
            }))


    class Meta:
        model = Exam
        fields = ('title', 'body', 'question','sampleSol', 'due')
        widgets = {
            'due': DateInput(),
        }



class ExamSolutionForm(forms.ModelForm):
    answer = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '5',
                   'placeholder': 'Write your Answer here...',
                   'class':'form-control'}
        ))

    class Meta:
        model = ExamSolution
        fields = ['answer']

exam/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from .forms import ExamForm, ExamSolutionForm
from .models import Exam, ExamSolution
from django.views import View
from django.urls import reverse_lazy

import nltk

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.corpus import wordnet
# Create your views here.


def exam_list(request):
    assignments = Exam.objects.all().order_by('-due')
    return render(request, 'exam/exam_list.html', {
        'assignments': assignments
    })

def upload_exam(request):
    if request.method == 'POST':
        form = ExamForm(request.POST, request.FILES)
        if form.is_valid():
            new_assignment = form.save(commit=False)
            new_assignment.author = request.user
            new_assignment.save()

    else:
        form = ExamForm()
    return render(request, 'exam/upload_exam.html', {
        'form': form
    })


class ExamDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        problem = Exam.objects.get(pk=pk)
        form = ExamSolutionForm()


        context = {
            'problem': problem,
            'form': form,
        }

        return render(request, 'exam/exam_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        print(request.POST)
        problem = Exam.objects.get(pk=pk)
        form = ExamSolutionForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.problem = problem
            new_comment.save()


        context = {
            'problem': problem,
            'form': form,
        }

        return render(request, 'exam/exam_detail.html', context)



def exam_evaluation_list(request):
    assignments = Exam.objects.all().order_by('-due')
    return render(request, 'exam/evaluation_list.html', {
        'assignments': assignments
    })



class EvaluationDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        prob = Exam.objects.get(pk=pk)

        solution = ExamSolution.objects.filter(problem=prob).order_by('-submission_time')

        context = {
            'problem': prob,
            'solution': solution,
        }

        return render(request, 'exam/solution_list.html', context)


class SolutionDetailView(View):
    def get(self, request, pk, *args, **kwargs):

        significance_level = 1.26
        solution = ExamSolution.objects.get(pk=pk)

        sampleSol = solution.problem.sampleSolution


        X = solution.answer
        Y = sampleSol

        punc = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

        # Using loop + punctuation string
        for ele in X:
            if ele in punc:
                X = X.replace(ele, "")


        for ele in Y:
            if ele in punc:
                Y = Y.replace(ele, "")


        X_list = word_tokenize(X)
        Y_list = word_tokenize(Y)

        sw = stopwords.words('english')

        l1 =[]
        l2 =[]

        # remove stop words from the string
        X_set = {w for w in X_list if not w in sw}
        Y_set = {w for w in Y_list if not w in sw}

        rvector = X_set.union(Y_set)
        # print(rvector)

        for w in rvector:

            synonyms = []

            for syn in wordnet.synsets(w):
	               for l in syn.lemmas():
		                 synonyms.append(l.name())


            for s in range(len(synonyms)):
                if synonyms[s] in X_set:
                    l1.append(1)
                    break
                else:
                    if s+1 == len(synonyms):
                        l1.append(0)

            for s in range(len(synonyms)):
                if synonyms[s] in Y_set:
                    l2.append(1)
                    break
                else:
                    if s+1 == len(synonyms):
                        l2.append(0)

        c=0

        for i in range(len(rvector)):
            c+= l1[i]*l2[i]

        cosine = c / float((sum(l1)*sum(l2))**0.5)
        cosine = cosine*significance_level*100


        context = {
            'solution': solution,
            'sampleSol': sampleSol,
            'result': cosine
        }

        return render(request, 'exam/solution_detail.html', context)



def Algorithm_detail(request):
    return render(request, 'exam/algorithm_detail.html', context={})

templates/exam/algorithm_detail.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}

<style media="screen">
  .jumbotron{
    text-align: center;
    padding-top: 10px;
  }
</style>

<div style="padding:15px">
  <div class="jumbotron">
    <strong style="font-size:32px">Cosine Similarity</strong><hr>
    <div style="font-size:20px; font-family: open sans regular">Cosine similarity measures the similarity between two vectors of an inner product space. It is measured by the cosine of the angle between two vectors and determines whether two vectors are pointing in roughly the same direction. It is often used to measure document similarity in text analysis. The cosine similarity is the cosine of the angle between vectors. The vectors are typically non-zero and are within an inner product space. The cosine similarity is described mathematically as the division between the dot product of vectors and the product of the euclidean norms or magnitude of each vector.
    </div><br><br>
    <img src="/media/design/cosine.png" alt="" width="500px" height="250px">
    <br><br><br>
    <strong style="font-size:28px">Formulas</strong><hr>
    <img src="/media/design/cosine_formula.png" alt="">
    <br><br><br>
    <strong style="font-size:28px">Algorithm</strong><hr>
    <div style="text-align:left">
      <ul class="list-group" style="font-family:open sans regular; font-size:20px">
      <li class="list-group-item">1. Fetch the Answer and the Sample Solution</li>
      <li class="list-group-item">2. Tokenize each word and then remove the Stopwords</li>
      <li class="list-group-item">3. Prepare a word collection list 'Rvector' from the Answer and the Sample Solution</li>
      <li class="list-group-item">4. Vectorize the Answer and the Sample Solution using the Rvector</li>
      <li class="list-group-item">5. While vectorization check for the synonyms as well. If a synonym is present then vectorize it as True</li>
      <li class="list-group-item">6. Put the counted 2 vectors(Answer & Sample Solution) into the Cosine Similarity formula</li>
      </ul>
    </div>
  </div>
  <br><br><br>
  <div style="padding:15px">
    <div class="jumbotron" style="padding-top:20px">
      <strong style="font-size:32px">Fuzzy String Matching</strong><hr>
      <div style="font-size:20px; font-family: open sans regular">Fuzzy string matching is the technique of finding strings that match with a given string partially and not exactly. When a user misspells a word or enters a word partially, fuzzy string matching helps in finding the right word – as we see in search engines. The algorithm behind fuzzy string matching does not simply look at the equivalency of two strings but rather quantifies how close two strings are to one another.
      </div><br><br>
      <img src="/media/design/fuzzy1.png" alt="" width="500px" height="250px"><br><br>
      <img src="/media/design/fuzzy2.png" alt="" width="420px" height="200px">
      <br><br><br>
      <strong style="font-size:28px">Levenshtein Distance</strong><hr>
      <img src="/media/design/fuzzy_formula.png" alt="" width="800px" height="240px">
      <br><br><br>
      <strong style="font-size:28px">Algorithm Details</strong><hr>
      <div style="text-align:justified; font-family:open sans regular; font-size:18px; margin:50px">
        <p>One possible definition of the approximate string matching problem is the following: Given a pattern string {\displaystyle P=p_{1}p_{2}...p_{m}}P = p_1p_2...p_m and a text string {\displaystyle T=t_{1}t_{2}\dots t_{n}}T = t_1t_2\dots t_n, find a substring {\displaystyle T_{j',j}=t_{j'}\dots t_{j}}T_{j',j} = t_{j'}\dots t_j in T, which, of all substrings of T, has the smallest edit distance to the pattern P. A brute-force approach would be to compute the edit distance to P for all substrings of T, and then choose the substring with the minimum distance. However, this algorithm would have the running time O(n3 m).</p><br>
        <p>A better solution, which was proposed by Sellers[3], relies on dynamic programming. It uses an alternative formulation of the problem: for each position j in the text T and each position i in the pattern P, compute the minimum edit distance between the i first characters of the pattern, {\displaystyle P_{i}}P_{i}, and any substring {\displaystyle T_{j',j}}T_{j',j} of T that ends at position j. For each position j in the text T, and each position i in the pattern P, go through all substrings of T ending at position j, and determine which one of them has the minimal edit distance to the i first characters of the pattern P. Write this minimal distance as E(i, j). After computing E(i, j) for all i and j, we can easily find a solution to the original problem: it is the substring for which E(m, j) is minimal (m being the length of the pattern P). Computing E(m, j) is very similar to computing the edit distance between two strings.</p><br>
        <p>In fact, we can use the Levenshtein distance computing algorithm for E(m, j), the only difference being that we must initialize the first row with zeros, and save the path of computation, that is, whether we used E(i − 1,j), E(i,j − 1) or E(i − 1,j − 1) in computing E(i, j). In the array containing the E(x, y) values, we then choose the minimal value in the last row, let it be E(x2, y2), and follow the path of computation backwards, back to the row number 0. If the field we arrived at was E(0, y1), then T[y1 + 1] ... T[y2] is a substring of T with the minimal edit distance to the pattern P. Computing the E(x, y) array takes O(mn) time with the dynamic programming algorithm, while the backwards-working phase takes O(n + m) time. Another recent idea is the similarity join. When matching database relates to a large scale of data, the O(mn) time with the dynamic programming algorithm cannot work within a limited time. So, the idea is to reduce the number of candidate pairs, instead of computing the similarity of all pairs of strings. Widely used algorithms are based on filter-verification, hashing, Locality-sensitive hashing (LSH), Tries and other greedy and approximation algorithms. Most of them are designed to fit some framework (such as Map-Reduce) to compute concurrently.</p>
      </div>
      <hr>
    </div>
</div>

{% endblock %}

templates/exam/evaluation_list.html
{% extends 'gradesApp/base.html' %}

{% block body_block %}

<div style="color:white;margin-top:50px">

<h2>Exam List</h2>


<table class="table" style="color:white">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Message</th>
      <th>Due</th>
      <th>Download</th>
    </tr>
  </thead>
  <tbody>
    {% for material in assignments %}

      <tr>
        <td><a href="{% url 'exam:solution_list' material.pk %}">{{ material.title }}</a></td>
        <td>{{ material.author }}</td>
        <td>{{ material.body }}</td>
        <td>{{ material.due }}</td>
        <td><a href="{{ material.question.url }}" class="btn btn-primary btn-sm" target="_blank">Question</a></td>
      </tr>

    {% endfor %}
  </tbody>
</table>
</div>

{% endblock %}

templates/exam/exam_detail.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<div style="color:white;margin-top:50px">
<h2 style="text-align: center; padding:25px">Exam Solution Submission</h2><br>

  <div class="row justify-content-center mt-3">
    <div class="col-mid-5 col-sm-12">
      <p><strong>{{ problem.author }}</strong> {{ problem.created_on }}</p>
      <h4>{{ problem.body }}</h4><hr><br>
    </div>
  </div>


  <div class="row justify-content mt-3 mb-5">
    <div class="col-md-5 col-sm-12 border-bottom">
      <form class="" method="POST" style="color:white">
        {% csrf_token %}
        {{ form | crispy }}
        <div class="d-grid gap-2">
          <button type="submit" id="submit" class="btn btn-primary mt-3" onclick="myFunction()">Submit Solution</button>
        </div>
        <br>
      </form>
    </div>
  </div>
</div>

{% endblock %}

templates/exam/exam_list.html
{% extends 'gradesApp/base.html' %}

{% block body_block %}
<div style="color:white;margin-top:50px">
<h2 style="color:white;margin-top:50px">Exam</h2>


<table class="table" style="color:white">
  <thead>
    <tr>
      <th>Title</th>
      <th>Uploaded By</th>
      <th>Message</th>
      <th>Due</th>
      <th>Download</th>
    </tr>
  </thead>
  <tbody>
    {% for material in assignments %}

      <tr>
        <td><a href="{% url 'exam:exam_detail' material.pk %}">{{ material.title }}</a></td>
        <td>{{ material.author }}</td>
        <td>{{ material.body }}</td>
        <td>{{ material.due }}</td>
        <td><a href="{{ material.question.url }}" class="btn btn-primary btn-sm" target="_blank">Question</a></td>
      </tr>

    {% endfor %}
  </tbody>
</table>

</div>
{% endblock %}

templates/exam/solution_detail.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<div style="color:white;margin-top:50px">
<h2 style="text-align:center; padding:25px">Evaluation</h2>

<div class="row justify-content-center mt-3">
  <div class="col-mid-5 col-sm-12">
    <div style="text-align:center">{{ solution.author }}<br> {{ solution.submission_time }}</div>
    <h2 style="text-align:center; padding:25px">Student's Answer</h2>
    <div class="jumbotron" style="color:black">{{ solution.answer }}<hr></div><br>
    <h2 style="text-align:center; padding:25px">Sample Answer</h2>
    <div class="jumbotron" style="color:black">{{ sampleSol }}<hr></div><br>
    <h2 style="text-align:center; padding:25px">Machine Evaluation Result</h2>
    <div class="jumbotron" style="color:black"><div style="text-align:center; font-size:20px">
      <strong>Similarity: </strong><strong style="color:blue">{{ result }}</strong>
      <b style="color:blue"> %</b><br><br>
      <a href="{% url 'exam:algorithm_detail' %}" class="btn btn-info">See Algorithm Details</a></div><hr>
    </div><br>

  </div>
</div>
</div>
{% endblock %}

templates/exam/solution_list.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<div style="color:white;margin-top:50px">
<h1 style="text-align:center; padding:40px; color: #191970" class="jumbotron">|| Solution List ||</h1>


<div class="row justify-content-center mt-3">
  <div class="col-mid-5 col-sm-12">
    <p><strong>Title: </strong>{{ problem.title }}<br>
    <b>Due: </b>{{ problem.due }}</p>
  </div>
</div>


    <table class="table" style="color:white">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Student Name</th>
          <th scope="col">Submission Time</th>
          <th scope="col">View Answer</th>
        </tr>
      </thead>
      <tbody>
        {% for solution in solution %}
          <tr>
            <td>{{ solution.author }}</td>
            <td>{{ solution.submission_time }}</td>
            <td><a href="{% url 'exam:solution_detail' solution.pk %}" class="btn btn-info">Evaluate Answer</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

templates/exam/upload_exam.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<h2 style="color:white;margin-top:50px">Create Exam</h2>
<form method="post" enctype="multipart/form-data" style="color:white;margin-top:50px">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Upload</button>
</form>

{% endblock %}