Post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView

app_name='Post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

chatbot/urls.py
from django.urls import path
from chatbot import views


app_name='chatbot'

urlpatterns = [

    path('', views.chat,name='chatbot')

]

gradesApp/urls.py
from django.urls import path
from gradesApp import views

app_name='gradesApp'

urlpatterns = [
    path('',views.index,name='index'),
    path('register/',views.register,name='register'),
    path('registerStudent/',views.registerStudent,name='registerStudent'),
    path('registerTeacher/',views.registerTeacher,name='registerTeacher'),
    path('login/',views.userLogin,name='userLogin'),
    path('dashboard/',views.studentDash,name='dashboard'),
    path('profile/', views.edit_profile, name='edit'),
    path('profileDetails/', views.viewProfile, name='viewProfile'),
    path('coursePage/', views.CoursePage, name='courseList'),

]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from gradesApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gradesApp/',include('gradesApp.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('logout/',views.userLogout,name='logout'),
    path('studentDash/',views.studentDash,name='studentDash'),
    path('teacherDash/',views.teacherDash,name='teacherDash'),
    path('materials/', include('upload.urls')),
    path('post/', include('Post.urls')),
    path('assignment/', include('assignment.urls')),
    path('notice/', include('Notice.urls')),
    path('exam/', include('exam.urls')),
    path('zoom/', include('zoom.urls')),
    path('onlineExam/', include('onlineExam.urls')),
    path('chatbot/', include('chatbot.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

gradesApp/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

class Student(models.Model):
    student=models.OneToOneField(User,on_delete=models.CASCADE)
    idno=models.IntegerField(blank=False)
    semester=models.CharField(max_length=256,blank=False)
    is_student=models.BooleanField(default=True)

    def __str__(self):
        return self.student.username

class Teacher(models.Model):
    teacher=models.OneToOneField(User,on_delete=models.CASCADE)
    phone=models.IntegerField()
    is_student=models.BooleanField(default=False)

    def __str__(self):
        return self.teacher.username


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='user_profile')
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)
    attendance = models.IntegerField()

gradesApp/forms.py
from django import forms
from django.contrib.auth.models import User
from gradesApp.models import Student,Teacher, UserProfile

class studentForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'})
        }

BRANCH_CHOICES = (
    ('1','1'),
    ('2','2'),
    ('3','3'),
    ('4','4'),
    ('5','5'),
    ('6','6'),
    ('7','7'),
    ('8','8'),

)
class studentAddForm(forms.ModelForm):
    semester=forms.CharField(widget=forms.Select(choices=BRANCH_CHOICES))
    class Meta():
        model=Student
        fields=['idno','semester']
        widgets = {
            'idno': forms.NumberInput(attrs={'class': 'form-control'}),
            'semester': forms.Select(attrs={'class': 'form-control'})
        }

class teacherForm(forms.ModelForm):
    password=forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
    class Meta():
        model=User
        fields=['first_name','last_name','username','email','password']
        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control'})
        }

class teacherAddForm(forms.ModelForm):
    class Meta():
        model=Teacher
        fields=['phone']
        widgets = {
            'phone': forms.TextInput(attrs={'class': 'form-control'})
        }


class EditProfile(forms.ModelForm):
    class Meta():
        model=UserProfile
        fields = "__all__"
        exclude = ('user',)

gradesApp/views.py
from django.shortcuts import render,redirect
from gradesApp.forms import studentForm,studentAddForm,teacherForm,teacherAddForm,EditProfile
from django.http import HttpResponse,HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from gradesApp.models import Student,Teacher,UserProfile
from django.contrib.auth.models import User

# Create your views here.

def index(request):
    return render(request,'gradesApp/index.html')

@login_required
def userLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register(request):
    return render(request,'gradesApp/register.html')

def registerStudent(request):
    registered=False
    if request.method=='POST':
        var_studentForm=studentForm(request.POST)
        var_studentAddForm=studentAddForm(request.POST)
        if var_studentForm.is_valid() and var_studentAddForm.is_valid():
            studentprimary=var_studentForm.save()
            studentprimary.set_password(studentprimary.password)
            studentprimary.save()
            studentAdd=var_studentAddForm.save(commit=False)
            studentAdd.student=studentprimary
            studentAdd.save()
            registered=True
    else:
        var_studentForm=studentForm()
        var_studentAddForm=studentAddForm()
    return render(request,'gradesApp/registerStudent.html',{'var_studentForm':var_studentForm,'var_studentAddForm':var_studentAddForm,'registered':registered})


def registerTeacher(request):
    registered=False
    if request.method=='POST':
        var_teacherForm=teacherForm(request.POST)
        var_teacherAddForm=teacherAddForm(request.POST)
        if var_teacherForm.is_valid() and var_teacherAddForm.is_valid():
            teacherprimary=var_teacherForm.save()
            teacherprimary.set_password(teacherprimary.password)
            teacherprimary.save()
            teacherAdd=var_teacherAddForm.save(commit=False)
            teacherAdd.teacher=teacherprimary
            teacherAdd.save()
            registered=True
    else:
        var_teacherForm=teacherForm()
        var_teacherAddForm=teacherAddForm()
    return render(request,'gradesApp/registerTeacher.html',{'var_teacherForm':var_teacherForm,'var_teacherAddForm':var_teacherAddForm,'registered':registered})

def userLogin(request):
    invalidlogin=False
    if request.method=='POST':
        username=request.POST.get('username')
        password=request.POST.get('password')
        user=authenticate(username=username,password=password)
        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/gradesApp/coursePage')
            else:
                return HttpResponse('Account not active')
        else:
            invalidlogin=True
            return redirect('/gradesApp/login/')
    else:
        return render(request,'gradesApp/login.html',{'invalidlogin':invalidlogin})

@login_required
def dashboard(request):
    try:
        current=Student.objects.get(student=request.user)
    except Student.DoesNotExist:
        current=Teacher.objects.get(teacher=request.user)
    if current.is_student:
        return redirect('/studentDash/')
    else:
        return redirect('/teacherDash/')
    return render(request,'gradesApp/dashboard.html')



def studentDash(request):
    return render(request,'gradesApp/courseList.html')

def teacherDash(request):
    return render(request,'gradesApp/courseList.html')


@login_required
def edit_profile(request):
    current_user = UserProfile.objects.get(user=request.user)
    form = EditProfile(instance=current_user)
    if request.method == 'POST':
        form = EditProfile(request.POST, request.FILES, instance=current_user)
        if form.is_valid():
            form.save(commit=True)
            form = EditProfile(instance=current_user)


    return render(request, 'gradesApp/profile.html', context={'form':form})


@login_required
def viewProfile(request):
    current_user = UserProfile.objects.get(user=request.user)

    context = {
        'profile': current_user
    }

    return render(request, 'gradesApp/viewProfile.html', context)


@login_required
def CoursePage(request):

    courseList = []
    courseCode = []

    try:
        current=Student.objects.get(student=request.user)
    except Student.DoesNotExist:
        current=Teacher.objects.get(teacher=request.user)
    if current.is_student:
        semester = current.semester
        if semester=='1':
            courseList = ['Structured Programming', 'Discrete Mathematics', 'Probability & Statistics', 'Sociology', 'Introduction to Software Engineering', 'Calculus & Analytical Geometry']
            courseCode = ['CSE 101', 'CSE 102', 'STAT 103', 'MATH 104', 'GE 105', 'SE 106']
        elif semester=='2':
            courseList = ['Data Structure and Algorithm', 'Computer Organization', 'Probability and Statistics for Engineers II', 'Ordinary Differential Equations', 'Bangladesh Studies', 'Object Oriented Concepts I']
            courseCode = ['CSE 201', 'CSE 211', 'STAT 203', 'MATH 204', 'GE 212', 'SE 206']
        elif semester=='3':
            courseList = ['Combinatorial Optimization', 'Theory of Computing', 'Computer Networking', 'Numerical Analysis for Engineers', 'Software Project Lab I', 'Object Oriented Concepts II']
            courseCode = ['CSE 301', 'SE 312', 'CSE 311', 'MATH 304', 'SE 305', 'SE 306']
        elif semester=='4':
            courseList = ['Operating System and System Programming', 'Business Psychology', 'Information Security', 'Database Management System I', 'Business Studies for Engineers ', 'Software Requirements Specification and Analysis']
            courseCode = ['CSE 401', 'GE 402', 'CSE 411', 'CSE 404', 'BUS 405', 'SE 406']
        elif semester=='5':
            courseList = ['Professional Ethics for Information Systems', 'Web Technology', 'Business Communications', 'Database Management System II', 'Software Project Lab II', 'Design Patterns']
            courseCode = ['SE5 11', 'CSE 502', 'BUS 503', 'CSE 504', 'SE 505', 'SE 506']
        elif semester=='6':
            courseList = ['Distributed Systems', 'Software Metrics', 'Software Security', 'Artificial Intelligence', 'Software Testing and Quality Assurance', 'Software Design and Analysis']
            courseCode = ['CSE 601', 'SE 611', 'SE 612', 'CSE 604', 'SE 605', 'SE 606']
        elif semester=='7':
            courseList = ['Internship']
            courseCode = ['SE 701']
        else:
            courseList = ['Project', 'Software Maintenance', 'Software Project Management', 'Machine Learning', 'Embedded Systems']
            courseCode = ['SE 801', 'SE 811', 'SE 803', 'CSE 837', 'CSE 823']
    else:
        courseList = ['Introduction to Software Engineering', 'Professional Ethics for Information Systems', 'Software Metrics']


    return render(request, 'gradesApp/coursePage.html', context={
        'courseList': courseList,
        'courseCode': courseCode
    })

templates/gradesApp/base.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    {% comment %} <link rel="stylesheet" href="{% static "CSS/mystyle.css" %}"> {% endcomment %}
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>E-shcool</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  <style>
    .main{
      background: linear-gradient(to bottom, rgba(0,0,0,0.9) 0%,rgba(0,0,0,0.9) 100%), url("/media/design/background2.jpg") no-repeat fixed;
      padding: 0 0 0 0;
      }
      
    .float{
      position:fixed;
      width:80px;
      height:60px;
      top:80px;
      right:80px;
      background-color:#f5c71a;
      color:#000;
      border-radius:50px;
      vertical-align:center;
      box-shadow: 2px 2px 3px yellow;
      padding:9px 14px;
      animation: float 1s;
      animation-iteration-count: infinite;
    }
    .float:hover{
      background-color:#ffb000;
    }
    
    @keyframes float {
      0% { transform: translate(1px, 1px) rotate(0deg); }
      10% { transform: translate(-1px, -2px) rotate(-1deg); }
      20% { transform: translate(-3px, 0px) rotate(1deg); }
      30% { transform: translate(3px, 2px) rotate(0deg); }
      40% { transform: translate(1px, -1px) rotate(1deg); }
      50% { transform: translate(-1px, 2px) rotate(-1deg); }
      60% { transform: translate(-3px, 1px) rotate(0deg); }
      70% { transform: translate(3px, 1px) rotate(-1deg); }
      80% { transform: translate(-1px, -1px) rotate(1deg); }
      90% { transform: translate(1px, 2px) rotate(0deg); }
      100% { transform: translate(1px, -2px) rotate(-1deg); }
    }
  </style>
</head>
<body class="main">
  <div class="main">
    <nav id = "navv" class="navbar navbar-expand-sm navbar-dark bg-dark">
      <a class="navbar-brand" href="{% url "index" %}" style="padding-left:50px"><b class="lead">E-shcool</b></a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation"></button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">

                {% if user.is_authenticated %}
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url "gradesApp:courseList" %}">Home</a>
                  </li>
                  <li class="nav-item active">
                    <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
                  </li>
                {% else %}
                <li class="nav-item active">
                  <a class="nav-link" href="{% url "admin:index" %}">Admin</a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link" href="{% url "gradesApp:register" %}">Register</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                    <li class="nav-item active ml-auto">
                        <a class="nav-link" href="{% url "logout" %}">Logout</a>
                    </li>
                    <div style="color:red; float:right">
                    <li>
                      <a class="nav-link" href="{% url "gradesApp:viewProfile" %}"><img src="/media/profile_pics/generalDP.jpg" width="30px" height="30px" class="rounded-circle" class="justify-content-end"/></a>
                    </li>
                    </div>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url "gradesApp:userLogin" %}"
                        >Login</a
                        >
                    </li>
                {% endif %}

            </ul>

        </div>
    </nav>
    <a target="_blank" id="botlink" href="{% url "chatbot:chatbot" %}" class="float">
      <img src="/media/design/bot.png" height="50px" width="50px"/>
    </a>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>
  </div>
</body>
</html>

templates/gradesApp/coursePage.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}
<style>
  .card {
    background: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 0.2) 0%,
      rgba(0, 0, 0, 0.2) 100%
    );
    transform: translate(0, -40%);
    padding: 25px;
  }
  .card:hover{
    z-index:10;
  }
</style>

{% for course in courseList %}
<div style="padding-right:20px; margin-top:150px">
<div class="card" style="width: 13rem; height: 18rem; float:left; margin:15px">
  <img class="card-img-top" src="/media/design/course.png" alt="Card image cap">
  <div class="card-body">
    <a style="color:white" href="{% url 'Post:post-list' %}">{{ course }}</a>
  </div>
</div>
</div>
{% endfor %}




{% endblock %}

templates/gradesApp/dashboard.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}
{% endblock %}

templates/gradesApp/index.html
{% extends 'gradesApp/base.html' %} {% block body_block %} {% load static %}
<style>
  .display-3 {
    text-align: center;
    color: #f5c71a;
    font-weight: bold;
    animation: display-3 2s ease infinite;
  }
  @keyframes display-3 {
    0% {
      transform: scale(1, 1);
    }
    50% {
      transform: scale(1.3, 1.3);
    }
    100% {
      transform: scale(1, 1);
    }
  }
</style>

<div
  style="
    position: absolute;
    top: 50%;
    right: 10%;
    left: 10%;
    transform: translate(0, -40%);
    padding: 25px;
  "
>
  <div class="text-primary">
    <h1 class="display-3">E-shcool</h1>
    <br />
    <hr />
  </div>
  <div>
    <p
      class="lead"
      style="
        text-align: center;
        padding-bottom: 15px;
        color: white;
        margin-top: 10px;
      "
    >
      An online-based educational platform to provide a learning environment to
      the students and<br />
      to ensure the academic experience virtually to both students and teachers
    </p>
    <hr class="my-2" />
  </div>
</div>

{% comment %}
<script>
  var nav = document.getElementById("navv");
  nav.style.display = "none";
</script>
{% endcomment %} {% endblock %}

templates/gradesApp/login.html
{% extends "gradesApp/base.html" %} {% block body_block %}

<style>
  .jumbotron {
    background: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 0.6) 0%,
      rgba(0, 0, 0, 0.6) 100%
    );
    position: absolute;
    top: 45%;
    right: 35%;
    left: 35%;
    transform: translate(0, -40%);
    padding: 25px;
    display:flex;
    flex-direction:column;
    justify-content:center;
    color:#f7f7f7;
  }
</style>

<div class="jumbotron">
  <h1
    class="display-3"
    style="font-size: 25px; color: #f5c71a; text-align: center"
  >
    <b>E-shcool</b>
  </h1>
  <h1 class="display-6 text-secondary" style="text-align: center">Login</h1>
  <hr />
  <br />

  {% if invalidlogin %}
  <h3>Please enter correct login details!</h3>
  {% endif %}
  <div>
  <form action="{% url 'gradesApp:userLogin' %}" method="POST">
    {% csrf_token %}
    <div style="display:flex;flex-direction:column;justify-content:center;">
    
    <div>
      <div style="margin-left:50px">
        <label for="username">Username: </label>
        <input class="form-control" style="width:300px" type="text" name="username" placeholder="Enter Username" />
      </div>
    </div>

    <div>
    <div style="margin-left:50px;margin-top:10px">
      <label for="password">Password: </label>
      <input
        class="form-control"
        type="password"
        name="password"
        placeholder="Enter Password"
        style="width:300px;"
      />
    </div>
    </div>

    <div>
    <div class="" style="text-align: center; padding-bottom: 20px">
      <input
        type="Submit"
        value="Login"
        class="btn btn-lg"
        style="
          background-color: transparent;
          border: 1px solid white;
          color: white;
          margin-top:50px
        "
      />
    </div>
  </form>
</div>
</div>

{% endblock %}

templates/gradesApp/profile.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}


<form method="POST" enctype="multipart/form-data">
  {{form|crispy}}
  {% csrf_token %}
  <button type="submit" name="button" class="btn btn-primary">Submit</button>
</form>


{% endblock %}

templates/gradesApp/register.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<style>
  .jumbotron{
    background: linear-gradient(to bottom, rgba(0,0,0,0.6) 0%,rgba(0,0,0,0.6) 100%);
    position: absolute;
    top: 40%;
    right: 30%;
    left: 30%;
    transform:
    translate(0, -40%);
    padding: 25px;
  }
</style>

<div class="jumbotron" style="">
    <h1 class="display-3" style="font-size:25px;color:#f5c71a ;text-align: center"><b>E-shcool</b></h1>
    <h1 class="display-6 text-secondary" style="text-align: center">Registration</h1>

    <hr class="my-2">
    <div class="lead" style="text-align: center; padding-bottom: 50px; padding-top: 40px; display: flex;justify-content: center;">
        <div class="" style="padding:10px">
          <a class="btn btn-lg" style="background-color:transparent;border:1px solid white; color:white" href="{% url "gradesApp:registerStudent" %}" role="button">I'm a Student</a>
        </div>
        <div class="" style="padding:10px">
          <a class="btn btn-lg" style="background-color:transparent;border:1px solid white; color:white" href="{% url "gradesApp:registerTeacher" %}" role="button">I'm a Teacher</a>
        </div>


    </div>
</div>

{% endblock %}

templates/gradesApp/registerStudent.html
{% extends 'gradesApp/base.html' %} {% block body_block %}
<style>
  .form-control {
    width: 500px;
  }
  .form-control:focus {
    border-color: #f5c71a;
  }
  .form-g {
    display: flex;
    flex-direction: column;
    justify-content: left;
  }
  .btn btn-success:hover {
    background-color: #f5c71a;
  }
  .jumbotron {
    background: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 0.2) 0%,
      rgba(0, 0, 0, 0.2) 100%
    );
    position: absolute;
    margin-top: 300px;
    right: 20%;
    left: 20%;
    transform: translate(0, -40%);
    padding: 25px;
    display: flex;
    justify-content: center;
  }
</style>
<div class="jumbotron">
  {% if registered %}
  <h1 class="lead" style="color: white">
    Thanks for registering, Please Log in!
  </h1>
  {% else %}
  <p
    class="display-4"
    style="color: #f5c71a; text-align: center; margin-top: 200px"
  >
    Sign Up for Students
  </p>
  <br />
  <form action="" method="POST">
    <div class="container lead" style="color: #f7f7f7; font-size: 15px">
      {% csrf_token %} {{ var_studentForm.as_p }} {{ var_studentAddForm.as_p }}
      <input
        type="submit"
        value="Register"
        class="btn btn-success"
        style="
          background-color: transparent;
          border: 1px solid white;
          color: white;
        "
      />
    </div>
  </form>
  {% endif %}
</div>

{% endblock %}

templates/gradesApp/registerTeacher.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<style>
    .form-control {
      width: 500px;
    }
    .form-control:focus {
      border-color: #f5c71a;
    }
    .form-g {
      display: flex;
      flex-direction: column;
      justify-content: left;
    }
    .btn btn-success:hover {
      background-color: #f5c71a;
    }
    .jumbotron {
      background: linear-gradient(
        to bottom,
        rgba(0, 0, 0, 0.2) 0%,
        rgba(0, 0, 0, 0.2) 100%
      );
      position: absolute;
      margin-top: 300px;
      right: 20%;
      left: 20%;
      transform: translate(0, -40%);
      padding: 25px;
      display: flex;
      justify-content: center;
    }
  </style>

<div class="jumbotron">
   {% if registered %}
        <h1 class="lead" style="color: white">Thanks for registering, Please Log in!</h1>
    {% else %}
        <p class="display-4"
        style="color: #f5c71a; text-align: center; margin-top: 200px">Sign Up for Teachers</p>
        <form action="" method="POST">
            <div class="container lead" style="color: #f7f7f7; font-size: 15px">
            {% csrf_token %}
            {{ var_teacherForm.as_p }}
            {{ var_teacherAddForm.as_p }}
            <input type="submit" value="Register" class="btn btn-success"
            style="
              background-color: transparent;
              border: 1px solid white;
              color: white;
            ">
            </div>
        </form>
    {% endif %}
</div>


{% endblock %}

templates/gradesApp/studentDash.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Student Dash</h2>
        <hr>
    </div>
</div>


{% endblock %}

templates/gradesApp/teacherDash.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<div class="container">
    <div class="jumbotron">
        <h2>Teacher Dash</h2>
        <hr>
    </div>
</div>

{% endblock %}

templates/gradesApp/viewProfile.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

<div class="container" style="text-align: center; color: white">
  
  <br />
  <img style="margin-top:50px" height="300px" width="300px" src="/media/{{ profile.profile_pic }}" />
  <br /><br /><br />

  <h3 class="display-3" style="margin-top:30px;font-weight:bold; font-size:30px;color:white ;text-align: center">Attendance List</h3>
  <br />

  <table class="table" style="color:white;" border="1" align="center">
    <tr>
      <th>Course</th>
      <th>Attendance</th>
    </tr>
    <tr>
      <td>x</td>
      <td>{{ profile.attendance }}</td>
    </tr>
  </table>
</div>

{% endblock %}