Post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView

app_name='Post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

assignment/urls.py
from django.urls import path
from assignment import views
from assignment.views import AssignmentDetailView, AEvaluationDetailView, SolutionDetailView


app_name='assignment'

urlpatterns = [

    path('', views.assignment_list, name='assignment_list'),
    path('upload_assignment/', views.upload_assignment, name='upload_assignment'),
    path('assignment/<int:pk>/', AssignmentDetailView.as_view(), name='assignment_detail'),
    path('evaluation/', views.assignment_evaluation_list, name='a_evaluation_list'),
    path('evaluation/<int:pk>', AEvaluationDetailView.as_view(), name='a_solution_list'),
    path('evaluation/detail/<int:pk>', SolutionDetailView.as_view(), name='a_solution_detail'),

]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from gradesApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gradesApp/',include('gradesApp.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('logout/',views.userLogout,name='logout'),
    path('studentDash/',views.studentDash,name='studentDash'),
    path('teacherDash/',views.teacherDash,name='teacherDash'),
    path('materials/', include('upload.urls')),
    path('post/', include('Post.urls')),
    path('assignment/', include('assignment.urls')),
    path('notice/', include('Notice.urls')),
    path('exam/', include('exam.urls')),
    path('zoom/', include('zoom.urls')),
    path('onlineExam/', include('onlineExam.urls')),
    path('chatbot/', include('chatbot.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

assignment/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

class Assignment(models.Model):
    title = models.TextField()
    body = models.TextField()
    due = models.DateField()
    question = models.FileField(upload_to='assignments/')
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Solution(models.Model):
    answer = models.TextField()
    submission_time = models.DateTimeField(default=timezone.now)
    problem = models.ForeignKey('Assignment', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

assignment/forms.py
from django import forms
from .models import Assignment, Solution


class DateInput(forms.DateInput):
    input_type = 'date'



class AssignmentForm(forms.ModelForm):
    title = forms.CharField(
        label='Name',
        widget=forms.Textarea(attrs={
            'rows': '1',
            'placeholder': 'Enter Assignment Name',
            'class':'form-control'
            }))

    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '6',
            'placeholder': 'Say Something...',
            'class':'form-control'
            }))


    class Meta:
        model = Assignment
        fields = ('title', 'body', 'question', 'due')
        widgets = {
            'due': DateInput(),
        }



class SolutionForm(forms.ModelForm):
    answer = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '3',
                   'placeholder': 'Write your Answer here...',
                   'class':'form-control'
                   }
        ))

    class Meta:
        model = Solution
        fields = ['answer']

assignment/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse,HttpResponseRedirect
from django.urls import reverse
from django.core.files.storage import FileSystemStorage
from .forms import AssignmentForm, SolutionForm
from .models import Assignment, Solution
from django.views import View
from django.urls import reverse_lazy

# Create your views here.


def assignment_list(request):
    assignments = Assignment.objects.all().order_by('-due')
    return render(request, 'assignment/assignment_list.html', {
        'assignments': assignments
    })

def upload_assignment(request):
    if request.method == 'POST':
        form = AssignmentForm(request.POST, request.FILES)
        if form.is_valid():
            new_assignment = form.save(commit=False)
            new_assignment.author = request.user
            new_assignment.save()

    else:
        form = AssignmentForm()
    return render(request, 'assignment/upload_assignment.html', {
        'form': form
    })


class AssignmentDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        problem = Assignment.objects.get(pk=pk)
        form = SolutionForm()


        context = {
            'problem': problem,
            'form': form,
        }

        return render(request, 'assignment/assignment_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        print(request.POST)
        problem = Assignment.objects.get(pk=pk)
        form = SolutionForm(request.POST)

        if form.is_valid():
            print('xyz')
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.problem = problem
            new_comment.save()


        context = {
            'problem': problem,
            'form': form,
        }

        return render(request, 'assignment/assignment_detail.html', context)


def assignment_evaluation_list(request):
    assignments = Assignment.objects.all().order_by('-due')
    return render(request, 'assignment/a_evaluation_list.html', {
        'assignments': assignments
    })


class AEvaluationDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        prob = Assignment.objects.get(pk=pk)

        solution = Solution.objects.filter(problem=prob).order_by('-submission_time')

        context = {
            'problem': prob,
            'solution': solution,
        }

        return render(request, 'assignment/a_solution_list.html', context)


class SolutionDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        solution = Solution.objects.get(pk=pk)

        context = {
            'solution': solution,
        }

        return render(request, 'assignment/a_solution_detail.html', context)

templates/assignment/a_evaluation_list.html
{% extends 'gradesApp/base.html' %}

{% block body_block %}

<div style="color:white;margin-top:50px">
<h2 style="text-align:center; padding:25px">Assignment List</h2>


<table class="table" style="color:white">
  <thead>
    <tr>
      <th>Title</th>
      <th>Author</th>
      <th>Message</th>
      <th>Due</th>
      <th>Download</th>
    </tr>
  </thead>
  <tbody>
    {% for material in assignments %}

      <tr>
        <td><a href="{% url 'assignment:a_solution_list' material.pk %}">{{ material.title }}</a></td>
        <td>{{ material.author }}</td>
        <td>{{ material.body }}</td>
        <td>{{ material.due }}</td>
        <td><a href="{{ material.question.url }}" class="btn btn-primary btn-sm" target="_blank">Question</a></td>
      </tr>

    {% endfor %}
  </tbody>
</table>
</div>

{% endblock %}

templates/assignment/a_solution_detail.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}

<h2 style="text-align:center">Evaluation</h2>

<div class="row justify-content-center mt-3">
  <div class="col-mid-5 col-sm-12">
    <div style="text-align:center">{{ solution.author }}<br> {{ solution.submission_time }}</div>
    <h2 style="text-align:center; padding:25px">Student's Answer</h2>
    <div class="jumbotron">{{ solution.answer }}<hr></div><br>
  </div>
</div>

{% endblock %}

templates/assignment/a_solution_list.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}
<div style="color:white;margin-top:50px">
<h1 style="text-align:center; padding:40px; color: #191970" class="jumbotron">|| Assignment Solution List ||</h1>


<div class="row justify-content-center mt-3">
  <div class="col-mid-5 col-sm-12">
    <p><strong>Title: </strong>{{ problem.title }}<br>
    <b>Due: </b>{{ problem.due }}</p>
  </div>
</div>


    <table class="table" style="color:white">
      <thead class="thead-dark">
        <tr>
          <th scope="col">Student Name</th>
          <th scope="col">Submission Time</th>
          <th scope="col">View Answer</th>
        </tr>
      </thead>
      <tbody>
        {% for solution in solution %}
          <tr>
            <td>{{ solution.author }}</td>
            <td>{{ solution.submission_time }}</td>
            <td><a href="{% url 'assignment:a_solution_detail' solution.pk %}" class="btn btn-info">Evaluate Answer</a></td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

{% endblock %}

templates/assignment/assignment_detail.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}

<div style="color:white;margin-top:50px">

  <div class="row justify-content-center mt-3">
    <div class="col-mid-5 col-sm-12">
      <p><strong>{{ problem.author }}</strong> {{ problem.created_on }}</p>
      <h4><b>{{ problem.body }}</b></h4><hr><br>
    </div>
  </div>


  <div class="row justify-content mt-3 mb-5">
    <div class="col-md-5 col-sm-12 border-bottom">
      <form class="" method="POST">
        {% csrf_token %}
        {{ form | crispy }}
        <div class="d-grid gap-2">
          <button class="btn btn-primary mt-3">Submit Solution</button>
        </div>
        <br>
      </form>
    </div>
  </div>


</div>
</div>

{% endblock %}

templates/assignment/assignment_list.html
{% extends 'gradesApp/base.html' %}

{% block body_block %}
<div style="color:white;margin-top:50px">
<h2>Assignments</h2>


<table class="table" style="color:white">
  <thead>
    <tr>
      <th>Title</th>
      <th>Uploaded By</th>
      <th>Message</th>
      <th>Due Time</th>
      <th>Download</th>
    </tr>
  </thead>
  <tbody>
    {% for material in assignments %}

      <tr>
        <td><a href="{% url 'assignment:assignment_detail' material.pk %}">{{ material.title }}</a></td>
        <td>{{ material.author }}</td>
        <td>{{ material.body }}</td>
        <td>{{ material.due }}</td>
        <td><a href="{{ material.question.url }}" class="btn btn-primary btn-sm" target="_blank">Question</a></td>
      </tr>

    {% endfor %}
  </tbody>
</table>

</div>
{% endblock %}

templates/assignment/upload_assignment.html
{% extends 'gradesApp/base.html' %}
{% block body_block %}

<h2 style="color:white;margin-top:50px">Create Assignment</h2>
<form method="post" enctype="multipart/form-data" style="color:white;margin-top:50px">
  {% csrf_token %}
  {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Upload</button>
</form>

{% endblock %}