Notice/urls.py
from django.urls import path
from Notice import views
from .views import NoticeDetail


app_name='Notice'

urlpatterns = [

    path('', views.notice_list, name='notice_list'),
    path('<int:pk>/', NoticeDetail.as_view(), name='notice_detail'),
]

Post/urls.py
from django.urls import path
from .views import PostListView, PostDetailView

app_name='Post'

urlpatterns = [
    path('', PostListView.as_view(), name='post-list'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
]

exam/urls.py
from django.urls import path
from exam import views
from exam.views import ExamDetailView, EvaluationDetailView, SolutionDetailView


app_name='exam'

urlpatterns = [

    path('', views.exam_list, name='exam_list'),
    path('upload_exam/', views.upload_exam, name='upload_exam'),
    path('evaluation/', views.exam_evaluation_list, name='evaluation_list'),
    path('<int:pk>/', ExamDetailView.as_view(), name='exam_detail'),
    path('evaluation/<int:pk>/', EvaluationDetailView.as_view(), name='solution_list'),
    path('evaluation/detail/<int:pk>', SolutionDetailView.as_view(), name='solution_detail'),
    path('evaluation/detail/algorithm', views.Algorithm_detail, name='algorithm_detail'),

]

myProject/urls.py
from django.contrib import admin
from django.urls import path, include
from gradesApp import views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('gradesApp/',include('gradesApp.urls')),
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    path('logout/',views.userLogout,name='logout'),
    path('studentDash/',views.studentDash,name='studentDash'),
    path('teacherDash/',views.teacherDash,name='teacherDash'),
    path('materials/', include('upload.urls')),
    path('post/', include('Post.urls')),
    path('assignment/', include('assignment.urls')),
    path('notice/', include('Notice.urls')),
    path('exam/', include('exam.urls')),
    path('zoom/', include('zoom.urls')),
    path('onlineExam/', include('onlineExam.urls')),
    path('chatbot/', include('chatbot.urls')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

upload/urls.py
from django.urls import path
from upload import views


app_name='upload'

urlpatterns = [

    path('', views.material_list, name='material_list'),
    path('upload_materials/', views.upload_material, name='upload_material'),

]

zoom/urls.py
from django.urls import path
from zoom import views


app_name='zoom'

urlpatterns = [

    path('', views.createForm, name='create_meeting'),
    path('form_list/', views.zoom_list, name='form_list'),

]

Post/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


class Post(models.Model):
    body = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)


class Comment(models.Model):
    comment = models.TextField()
    created_on = models.DateTimeField(default=timezone.now)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)
    author = models.ForeignKey(User, on_delete=models.CASCADE)

Post/forms.py
from django import forms
from .models import Post, Comment

class PostForm(forms.ModelForm):
    body = forms.CharField(
        label='',
        widget=forms.Textarea(attrs={
            'rows': '3',
            'placeholder': 'Say Something...',
            'class': 'md-textarea form-control'
            }))

    class Meta:
        model = Post
        fields = ['body']


class CommentForm(forms.ModelForm):
    comment = forms.CharField(
        label='',
        widget=forms.Textarea(
            attrs={'rows': '1',
                   'placeholder': 'Add a Comment...',
                   'class': 'md-textarea form-control'
                }
        ))

    class Meta:
        model = Comment
        fields = ['comment']

Post/views.py
from django.shortcuts import render
from django.views import View
from .models import Post, Comment
from .forms import PostForm, CommentForm
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib.auth import authenticate,login,logout
from gradesApp.models import Student,Teacher
from django.contrib.auth.models import User


class PostListView(View):
    def get(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-created_on')
        form = PostForm()
        val = False

        try:
            current=Student.objects.get(student=request.user)
            val = current.is_student
        except Student.DoesNotExist:
            current=Teacher.objects.get(teacher=request.user)


        context = {
            'post_list': posts,
            'form': form,
            'is_student': val,
        }

        return render(request, 'Post/post_list.html', context)

    def post(self, request, *args, **kwargs):
        posts = Post.objects.all().order_by('-created_on')
        form = PostForm(request.POST)

        if form.is_valid():
            new_post = form.save(commit=False)
            new_post.author = request.user
            new_post.save()
            form = PostForm(request.POST)
        val = False

        try:
            current=Student.objects.get(student=request.user)
            val = current.is_student
        except Student.DoesNotExist:
            current=Teacher.objects.get(teacher=request.user)

        context = {
            'post_list': posts,
            'form': form,
            'is_student':val,
        }

        return render(request, 'Post/post_list.html', context)




class PostDetailView(View):
    def get(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm()

        comments = Comment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'Post/post_detail.html', context)

    def post(self, request, pk, *args, **kwargs):
        post = Post.objects.get(pk=pk)
        form = CommentForm(request.POST)

        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.author = request.user
            new_comment.post = post
            new_comment.save()

        comments = Comment.objects.filter(post=post).order_by('-created_on')

        context = {
            'post': post,
            'form': form,
            'comments': comments,
        }

        return render(request, 'Post/post_detail.html', context)

templates/Post/post_detail.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}

{% block body_block %}

<style>
  #navv{
    display:none;
  }
  .main{
    background: linear-gradient(to bottom, rgba(0,0,0,0.9) 0%,rgba(0,0,0,0.9) 100%), url("/media/design/background2.jpg") no-repeat fixed;
    padding: 0 0 0 0;
    }
</style>

<div class="container" style="color:white">
  <div class="row mt-5" >
    <div class="col-md-5 col-sm-6" style="margin-top:50px;margin-bottom:100px;">
      <a style="color:white"class="nav-link" href="{% url 'Post:post-list' %}"><--Back</a>
    </div>
  </div>

  <div class="row justify-content-center mt-3">
    <div class="col-mid-5 col-sm-12">
      <h6 class="lead"><b>{{ post.author }}</b></h6> <p style="font-size:10px">{{ post.created_on }}</p>
      <p class="lead" style="margin-bottom:100px">{{ post.body }}</p>
      <h5>Comments</h5>
    </div>
  </div>

  {% for comment in comments %}

    <div class="row justify-content mt-3 mb-5 border-bottom">
      <div class="col-md-5 col-sm-12">
        <p><strong>{{ comment.author }} </strong>&emsp;{{ comment.created_on }}</p>
        <p>{{ comment.comment }}</p>
      </div>
    </div>

  {% endfor %}

  <div class="row justify-content mt-3 mb-5">
    <div class="col-md-5 col-sm-12 border-bottom">
      <form class="" method="POST" style="display:flex;flex-direction:column">
        {% csrf_token %}
        {{ form | crispy }}
        <div>
          <button class="btn btn-dark mt-3">Add Comment</button>
        </div>
        <br>
      </form>
    </div>
  </div>


</div>


{% endblock %}

templates/Post/post_list.html
{% extends 'gradesApp/base.html' %}
{% load crispy_forms_tags %}
{% block body_block %}

<script>
  function clicked(){
    forr = document.getElementById('ttt');
    form.reset();
  }
</script>
<style>
  .main{
    background: linear-gradient(to bottom, rgba(0,0,0,0.9) 0%,rgba(0,0,0,0.9) 100%), url("/media/design/background2.jpg") no-repeat fixed;
    padding: 0 0 0 0;
    }
  #ppp{
    background: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 0.2) 0%,
      rgba(0, 0, 0, 0.2) 100%
    );
    transform: translate(0, -40%);
    padding: 25px;
  }
  #post:hover{
    background: linear-gradient(
      to bottom,
      rgba(0, 0, 0, 0.2) 0%,
      rgba(0, 0, 0, 0.2) 100%
    );
  }
</style>
<div style="display:flex;">
<div id="ppp" class="nav flex-column" style="position:fixed; margin-top:300px;">
  {% if is_student %}
  <a href="{% url 'upload:material_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Course Materials</a
  >
  <a href="{% url 'Notice:notice_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a">Notice Board</a>
  <a href="{% url 'zoom:form_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Online Meetings</a
  >
  <a href="{% url 'assignment:assignment_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Assignments</a
  >
  <a href="{% url 'exam:exam_list' %}"  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a">Exams</a>
  <a href="{% url 'gradesApp:viewProfile' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Profile</a
  >
  <a href="{% url 'onlineExam:firstPage' %}"  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Join Online Exam</a
  >
  {% else %}
  <a href="{% url 'upload:material_list' %}"  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Course Materials</a
  >
  <a href="{% url 'upload:upload_material' %}"  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Upload Course Materials</a
  >
  <a href="{% url 'Notice:notice_list' %}"  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a">Notice Board</a>
  <a href=""  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a">Online Meetings</a>
  <a href="{% url 'assignment:upload_assignment' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
    >Create Assignment</a
  >
  <a href="{% url 'exam:upload_exam' %}"  class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a">Create Exam</a>
  
  <div style="padding-top: 0px">
    <a href="{% url 'exam:evaluation_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
      >Exam Evaluation</a
    >
    <a href="{% url 'assignment:a_evaluation_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
      >Assignment Evaluation</a
    >
    <a href="{% url 'zoom:form_list' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
      >Online Meetings</a
    >
    <a href="{% url 'zoom:create_meeting' %}" class="nav-link" style="margin-bottom:10px;width:200px;color:#f5c71a"
      >Create Online Meeting</a
    >
  </div>
  {% endif %}
</div>

<div class="container" style="margin-top:50px;color:white">
  <div class="row justify-content-center mt-3">
    <div style="margin-bottom:50px;">
      <h5 class="display-3 lead">Course Stream</h5>
    </div>
  </div>

  <div class="row justify-content-center mt-3 mb-5" style="">
    <div class="col-md-5 col-sm-12 border-bottom">
      <form id="ttt" class="" method="POST">
        {% csrf_token %} {{ form | crispy }}
        <div class="d-grid gap-2">
          <button style="background-color:transparent;border:1px solid #f5c71a;margin-left:370px;margin-bottom:100px" class="btn btn-success mt-3" onclick="clicked()">Post!</button>
        </div>
        <br />
      </form>
    </div>
  </div>

  {% for post in post_list %}
  <div id="post" class="row justify-content-center mt-3" style="margin-bottom:100px;width:wrap-content;">
    <div class="col-md-5 col-sm-12 border-bottom position-relative">
      <h6 class="lead"><b>{{ post.author }}</b></h6> <p style="font-size:10px">{{ post.created_on }}</p>
      <p class="lead">{{ post.body }}</p>
      <br />
      <a href="{% url 'Post:post-detail' post.pk %}" class="stretched-link"></a>
    </div>
  </div>
  {% endfor %}
</div>
</div>

{%endblock%}